// Auto-generated by expo-modules-autolinking (simulated for MVP)
// In production, this file is generated by the autolinking build step.

namespace Expo.Modules.Autolinking;

public static class ExpoModulesProvider
{
    public static Type[] GetModuleClasses() => new[]
    {
        typeof(ExampleModules.ExampleModule),
    };
}
